[package]
name = "lab01_chunk"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../../crates/common" }
datamodel = { path = "../../crates/datamodel" }
storage = { path = "../../crates/storage" }
